import { test, expect } from '@playwright/test'
test('real map sources, comparison, navigation, sources and mobile layout', async ({ page }) => {
  const failures: string[] = []
  page.on('pageerror', error => failures.push(error.message))
  const historicResponses: number[] = []
  page.on('response', response => { if(response.url().includes('tolosa-1680.pmtiles')) historicResponses.push(response.status()) })
  await page.goto('/')
  await expect(page.getByText('Карты загружены', { exact: true })).toBeVisible({ timeout: 60000 })
  await expect(page.getByRole('alert')).toHaveCount(0)
  expect(historicResponses.some(code => code === 206)).toBeTruthy()
  await page.screenshot({ path: '.local/desktop.png' })
  await page.getByRole('button', { name: 'Наложение', exact: true }).click()
  await page.getByRole('slider', { name: 'Непрозрачность исторической карты', exact: true }).fill('38')
  await expect(page.locator('.historic-map')).toHaveCSS('opacity', '0.38')
  await page.getByRole('button', { name: 'Сегодня', exact: true }).click()
  await expect(page.locator('.historic-map')).toHaveCSS('opacity', '0')
  await page.screenshot({ path: '.local/modern.png' })
  await page.getByRole('button', { name: '1680', exact: true }).click()
  await expect(page.locator('.historic-map')).toHaveCSS('opacity', '1')
  await page.screenshot({ path: '.local/historic.png' })
  await page.locator('h1').click()
  await page.keyboard.down('Space')
  await expect(page.locator('.historic-map')).toHaveCSS('opacity', '0')
  await page.keyboard.up('Space')
  await expect(page.locator('.historic-map')).toHaveCSS('opacity', '1')
  await page.getByRole('button', { name: 'Шторка', exact: true }).click()
  await page.getByRole('slider', { name: 'Положение шторки', exact: true }).fill('70')
  await expect(page.locator('.historic-map')).toHaveCSS('clip-path', 'inset(0px 30% 0px 0px)')
  await page.getByRole('combobox').selectOption('1')
  await expect(page).toHaveURL(/lat=43.599782/, { timeout: 10000 })
  await page.screenshot({ path: '.local/saint-etienne.png' })
  await page.getByRole('button', { name: 'Наложение', exact: true }).click()
  await page.getByRole('slider', { name: 'Непрозрачность исторической карты', exact: true }).fill('50')
  await page.screenshot({ path: '.local/alignment.png' })
  await page.getByRole('button', { name: 'Шторка', exact: true }).click()
  await page.getByRole('slider', { name: 'Граница сравнения карт', exact: true }).focus()
  await page.keyboard.press('ArrowLeft')
  await expect(page.locator('.historic-map')).toHaveCSS('clip-path', 'inset(0px 32% 0px 0px)')
  const oldUrl = page.url()
  await page.mouse.move(1100, 600)
  await page.mouse.down()
  await page.mouse.move(950, 650, { steps: 12 })
  await page.mouse.up()
  await expect.poll(() => page.url()).not.toEqual(oldUrl)
  const savedUrl = page.url()
  await page.reload()
  await expect(page.getByText('Карты загружены', { exact: true })).toBeVisible({ timeout: 60000 })
  expect(page.url()).toEqual(savedUrl)
  await page.getByRole('button', { name: 'О картах', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: '.local/mobile.png' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  await expect(page.getByRole('button', { name: 'Сегодня', exact: true })).toBeVisible()
  expect(failures).toEqual([])
})
test('historical network failure is explained', async ({ page }) => {
  await page.route('**/tolosa-1680.pmtiles', route => route.abort())
  await page.goto('/')
  await expect(page.getByRole('alert')).toContainText('Не удалось загрузить часть карты 1680 года', { timeout: 30000 })
})
