import { test, expect } from '@playwright/test'
test('continuous timeline preserves view, endpoints, keyboard peek and shared state', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  await page.goto('/#lon=1.44954&lat=43.597678&z=16.7')
  await expect(page.getByText('Карты загружены', { exact: true })).toBeVisible({ timeout: 60000 })
  await page.getByRole('button', { name: 'Время', exact: true }).click()
  const slider = page.getByRole('slider', { name: 'Путешествие по времени' })
  await expect(slider).toBeVisible()
  await expect(page.getByRole('slider', { name: 'Граница сравнения карт' })).toHaveCount(0)
  await slider.fill('1755')
  await expect(page.locator('.timeline-value')).toHaveText('1680 → 1830 · 50%')
  await expect(page).toHaveURL(/mode=time&time=1755/)
  await page.screenshot({ path: '.local/time-midpoint.png' })
  await slider.fill('1830')
  await expect(page.locator('.timeline-value')).toHaveText('1830')
  await page.screenshot({ path: '.local/time-1830.png' })
  const today = new Date().getFullYear()
  await slider.fill(String(today))
  await expect(page.locator('.timeline-value')).toHaveText('Сегодня')
  await page.screenshot({ path: '.local/time-today.png' })
  await slider.fill('1755')
  await page.reload()
  await expect(slider).toHaveValue('1755')
  await expect(page.getByText('Карты загружены', { exact: true })).toBeVisible({ timeout: 60000 })
  await page.locator('h1').click()
  await page.keyboard.down('Space')
  await expect(page.locator('.historic-map')).toHaveCSS('opacity', '0')
  await page.keyboard.up('Space')
  await expect(page.locator('.historic-map')).toHaveCSS('opacity', '1')
  await page.getByRole('button', { name: 'Шторка', exact: true }).click()
  await expect(page.getByRole('group', { name: 'Исторический период' })).toBeVisible()
  await page.getByRole('button', { name: 'Время', exact: true }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: '.local/time-mobile.png' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  await expect(page.getByRole('alert')).toHaveCount(0)
  expect(errors).toEqual([])
})
